POST http://localhost:1992/register
Content-Type: application/json

{
    "nome": "Petala",
    "senha": "petala123"
}

###

GET http://localhost:1992/users

###

POST http://localhost:1992/login
Content-Type: application/json

{
    "nome": "Agatha da Cunha",
    "senha": "5bt^4LClwOo"
}